# Generated by Django 3.2.25 on 2026-02-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customr',
            new_name='customer',
        ),
    ]
