# Generated by Django 3.2.25 on 2026-02-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_customr_payment_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
