# Generated by Django 3.2.25 on 2026-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20260203_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='post',
            field=models.CharField(default='', max_length=30),
        ),
    ]
