# Generated by Django 3.2.25 on 2026-02-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20260203_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='transection_id',
            field=models.IntegerField(),
        ),
    ]
