# Generated by Django 3.2.25 on 2026-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20260203_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transection_id',
            field=models.CharField(max_length=50),
        ),
    ]
